name: Test Report

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  test-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    
    steps:
    - name: Download artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.workflow_run.id }}
          });
          const testResults = artifacts.data.artifacts.find(
            artifact => artifact.name === "test-results"
          );
          if (!testResults) throw new Error("Test results not found");
          
          const download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: testResults.id,
            archive_format: 'zip'
          });
          
          const fs = require('fs');
          fs.writeFileSync('test-results.zip', Buffer.from(download.data));
          
    - name: Extract test results
      run: unzip test-results.zip

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Railway Signal Tests
        path: test_report.xml
        reporter: java-junit
        fail-on-error: true
