name: Test Report

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: test-results
          path: test-results

      - name: List Files
        run: |
          pwd
          ls -la
          ls -la test-results || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Railway Signal Tests
          path: test-results/*.xml
          reporter: java-junit
          fail-on-error: true
